server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/user/**, /api/favorite/**

        - id: anime-service
          uri: lb://anime-service
          predicates:
            - Path=/api/anime/**, /api/recommend/**, /api/search/**

        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**

        - id: danmaku-service
          uri: lb://danmaku-service
          predicates:
            - Path=/api/danmaku/**, /ws/**

        - id: crawler-service
          uri: lb://crawler-service
          predicates:
            - Path=/api/crawler/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://www.animeparadise.vip"
              - "https://animeparadise.vip"
              - "http://www.animeparadise.vip"
              - "http://animeparadise.vip"
              - "https://lsj.animeparadise.vip"
              - "http://lsj.animeparadise.vip"
              - "http://localhost"
              - "http://localhost:5173"
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://127.0.0.1"
              - "http://127.0.0.1:5173"
              - "http://127.0.0.1:3000"
              - "http://127.0.0.1:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
logging:
  level:
    com.anime: debug