# 主配置文件
spring:
  application:
    name: user-service
  profiles:
    # 默认激活开发环境，生产环境通过启动参数指定：--spring.profiles.active=prod
    active: dev

# MyBatis-Plus通用配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 日志通用配置
logging:
  level:
    com.anime: info
