server:
  port: 8086

spring:
  application:
    name: admin-service
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

file:
  upload:
    path: /root/uploads/app-versions/
  access:
    url: https://www.animeparadise.vip/files

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.anime: debug
