server:
  port: 8082

spring:
  application:
    name: anime-service

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.anime: debug


